SELECT A.CODCLI, A.RUT+'-'+C.DIG AS RUT,
       C.NOMBRE,
       C.PATERNO AS APELLIDO_PATERNO,
       C.MATERNO AS APELLIDO_MATERNO,
       A.ESTACAD AS ESTADO_ACADEMICO,
       A.ANO AS ANO_INGRESO,
       A.PERIODO AS PERIODO_INGRESO,
       A.CODCARPR AS COD_CARRERA,
       R.NOMBRE_L AS CARRERA,
       A.CODPESTUD AS CODIGO_PLAN_ESTUDIO,
       P.NOMPESTUD AS NOMBRE_PLANESTUDIOS,
       C.DIRACTUAL AS DIRECCION,
       C.COMUNA,
       C.CIUDADACT AS CIUDAD,
       C.MAIL AS MAIL_PERSONAL,
       C.MAIL_INST AS MAIL_INSTITUCIONAL,
       C.FONOACT AS TELEFONO,
       ISNULL(C.DISCAPACIDAD,'Ninguna') AS DISCAPACIDAD,
       (SELECT COUNT(1) FROM RA_NOTA X WHERE X.CODCLI=A.CODCLI AND ESTADO='A') RAMOS_APROBADOS,
       (SELECT COUNT(1) FROM RA_NOTA X WHERE X.CODCLI=A.CODCLI AND ESTADO='R') RAMOS_REPROBADOS,
       (CONVERT(VARCHAR(4),A.ANO_MAT)+'-'+CONVERT(VARCHAR(1),A.PERIODO_MAT)) AS ULT_MATRICULA
FROM MT_ALUMNO A
INNER JOIN MT_CLIENT C
ON A.RUT=C.CODCLI
INNER JOIN MT_CARRER R
ON A.CODCARPR=R.CODCARR
INNER JOIN MT_TIPOMAT T
ON R.TIPOMAT=T.TIPOMAT
INNER JOIN RA_PESTUD P
ON A.CODPESTUD=P.CODPESTUD
WHERE A.ESTACAD='VIGENTE' AND A.PERIODOS=1 AND R.TIPOCARR=1 AND
CONVERT(VARCHAR(4),A.ANO_MAT)+'-'+CONVERT(VARCHAR(1),A.PERIODO_MAT)<>'2026-2'    --CONVERT(VARCHAR(4),T.ANO_MAT)+'-'+CONVERT(VARCHAR(1),T.PERIODO_MAT)