FROM node:20-bookworm-slim AS base
WORKDIR /app
COPY package.json package-lock.json ./

FROM base AS builder
RUN npm ci
COPY . .
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_KEY
ARG VITE_API_URL
ARG VITE_SIMULADOR_SUPABASE_URL
ARG VITE_SIMULADOR_SUPABASE_ANON_KEY
ARG VITE_AUTH_ORIGIN
ARG VITE_AUTH_AMBIENTE
ARG VITE_MNP_MV_ANIO_MATRICULA
ARG VITE_MNP_MV_PERIODO_MATRICULA
ARG VITE_DEBUG_BO_MENU
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_KEY=$VITE_SUPABASE_KEY \
    VITE_API_URL=$VITE_API_URL \
    VITE_SIMULADOR_SUPABASE_URL=$VITE_SIMULADOR_SUPABASE_URL \
    VITE_SIMULADOR_SUPABASE_ANON_KEY=$VITE_SIMULADOR_SUPABASE_ANON_KEY \
    VITE_AUTH_ORIGIN=$VITE_AUTH_ORIGIN \
    VITE_AUTH_AMBIENTE=$VITE_AUTH_AMBIENTE \
    VITE_MNP_MV_ANIO_MATRICULA=$VITE_MNP_MV_ANIO_MATRICULA \
    VITE_MNP_MV_PERIODO_MATRICULA=$VITE_MNP_MV_PERIODO_MATRICULA \
    VITE_DEBUG_BO_MENU=$VITE_DEBUG_BO_MENU
RUN npm run build

FROM base AS dev
RUN npm ci
COPY . .
EXPOSE 9501
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "9501"]

FROM nginx:alpine AS production
COPY nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=builder /app/dist /usr/share/nginx/html
ENV REMATRICULA_API_KEY=""
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
