-- Staging matrícula MOL: espejo UMAS MT_DOCITEM / MT_CTADOC / MT_CTAPAG / MT_CTADEP.
-- Tipos Postgres round-trip con SQL Server. Sin FK de catálogo (CLIENT, CARRER, JORNADA, etc.).
-- Sin FK entre las 4 (inserts parciales mientras se arma el flujo).
-- Escritura vía service_role (uniacc-api); anon/authenticated no leen ni insertan.

-- ---------------------------------------------------------------------------
-- mnp_mt_docitem
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mnp_mt_docitem (
    keydocitem bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item numeric(3, 0) NOT NULL,
    ctadoc numeric(4, 0) NOT NULL,
    ctadocnum numeric(15, 0) NOT NULL,
    gastosop numeric(10, 0),
    intdeuda numeric(10, 0),
    ano numeric(4, 0) NOT NULL,
    periodo numeric(2, 0) NOT NULL,
    codcli varchar(30) NOT NULL,
    codcarr varchar(30) NOT NULL,
    tipocarr numeric(3, 0) NOT NULL,
    cantidad numeric(3, 0) NOT NULL,
    precio numeric(12, 2),
    feccom timestamp NOT NULL,
    usuario varchar(8) NOT NULL,
    estado numeric(3, 0) NOT NULL,
    fecmod timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ctatrans numeric(15, 0),
    monto numeric(12, 2),
    montoint numeric(12, 2),
    porcint numeric(5, 2),
    manual numeric(1, 0),
    fecnot timestamp,
    fecanulacion timestamp,
    num_operacion numeric(22, 0),
    glosa varchar(255),
    sede varchar(30),
    impreso varchar(2),
    moneda_ad numeric(1, 0),
    monto_ad numeric(18, 6),
    devengo_sem varchar(2),
    jornada varchar(10),
    created_at timestamptz NOT NULL DEFAULT now(),
    origen text NOT NULL DEFAULT 'mol'
);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_docitem_codcli_periodo
    ON public.mnp_mt_docitem (codcli, ano, periodo);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_docitem_num_operacion
    ON public.mnp_mt_docitem (num_operacion);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_docitem_ctadocnum
    ON public.mnp_mt_docitem (ctadocnum);

COMMENT ON TABLE public.mnp_mt_docitem IS
    'Staging MOL espejo UMAS MT_DOCITEM (ítems matrícula/arancel). No escribe en SQL Server.';

-- ---------------------------------------------------------------------------
-- mnp_mt_ctadoc
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mnp_mt_ctadoc (
    ctadoc numeric(4, 0) NOT NULL,
    ctadocnum numeric(15, 0) NOT NULL,
    codapod varchar(30) NOT NULL,
    codcli varchar(30) NOT NULL,
    contrato varchar(40),
    convenio numeric(10, 0),
    codcarr varchar(30) NOT NULL,
    cuota numeric(2, 0),
    numcuot numeric(2, 0),
    monto numeric(12, 2),
    saldo numeric(12, 2) DEFAULT 0,
    fecven timestamp,
    fecdeuda timestamp,
    estado numeric(2, 0) NOT NULL DEFAULT 2,
    ubicacion smallint,
    recibido varchar(1) NOT NULL,
    fecrep timestamp,
    codban numeric(5, 0) NOT NULL DEFAULT 0,
    codsuc numeric(2, 0),
    feccancel timestamp,
    intdeuda numeric(10, 0),
    intrepac numeric(10, 0),
    codnot numeric(2, 0),
    tipocarr numeric(3, 0) NOT NULL,
    ano numeric(4, 0) NOT NULL,
    periodo numeric(2, 0) NOT NULL,
    gastosop numeric(10, 0) NOT NULL DEFAULT 0,
    usuario varchar(8) NOT NULL,
    fecmod timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecreg timestamp,
    fecimp timestamp,
    ctatrans numeric(15, 0),
    numletra numeric(2, 0),
    fecnot timestamp,
    caja integer,
    fecanulacion timestamp,
    gastospro numeric(10, 0),
    item numeric(3, 0),
    fecha timestamp,
    turno numeric(18, 0),
    sede varchar(30),
    montopromocion double precision,
    montorecargo double precision,
    montodscto double precision,
    num_operacion numeric(22, 0) NOT NULL,
    por1 double precision,
    por2 double precision,
    por3 double precision,
    repactar varchar(1),
    codcuponera numeric(10, 0),
    obsestado varchar(50),
    montorenegociacion double precision,
    folioprorrog numeric(18, 0),
    foliodevol numeric(18, 0),
    foliorepactacion numeric(18, 0),
    cod_movdoc numeric(18, 0),
    foliopago numeric(18, 0),
    por4 double precision,
    fechatope timestamp,
    facturable varchar(1) DEFAULT 'N',
    ctadocref numeric(2, 0),
    ctadocnumref numeric(10, 0),
    codbanref numeric(5, 0),
    tipopagcond numeric(2, 0),
    fechaenvio timestamp,
    fechadevolucion timestamp,
    num_operacion2 numeric(22, 0),
    num_operacion3 numeric(22, 0),
    vctoori timestamp,
    ctacte varchar(50),
    rut_gir varchar(20),
    nom_girador varchar(50),
    fono_girador varchar(50),
    version numeric(2, 0),
    pac varchar(2) DEFAULT 'NO',
    letra numeric(2, 0),
    id_cuota bigint GENERATED BY DEFAULT AS IDENTITY,
    codalumno varchar(30),
    moneda_ad numeric(1, 0),
    monto_ad numeric(18, 6),
    saldo_ad numeric(18, 6),
    repactado char(2) DEFAULT 'NO',
    jornada varchar(10),
    created_at timestamptz NOT NULL DEFAULT now(),
    origen text NOT NULL DEFAULT 'mol',
    CONSTRAINT pk_mnp_mt_ctadoc PRIMARY KEY (ctadoc, ctadocnum, codapod, codcli, codban),
    CONSTRAINT ck_mnp_mt_ctadoc_pac CHECK (pac IS NULL OR pac IN ('NO', 'SI')),
    CONSTRAINT ck_mnp_mt_ctadoc_repactado CHECK (repactado IS NULL OR repactado IN ('NO', 'SI'))
);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctadoc_codcli_periodo
    ON public.mnp_mt_ctadoc (codcli, ano, periodo);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctadoc_num_operacion
    ON public.mnp_mt_ctadoc (num_operacion);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctadoc_ctadocnum
    ON public.mnp_mt_ctadoc (ctadocnum);

COMMENT ON TABLE public.mnp_mt_ctadoc IS
    'Staging MOL espejo UMAS MT_CTADOC (cuotas/documentos). No escribe en SQL Server.';

-- ---------------------------------------------------------------------------
-- mnp_mt_ctapag
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mnp_mt_ctapag (
    ctapag numeric(4, 0) NOT NULL,
    ctapagnum numeric(15, 0) NOT NULL,
    codcli varchar(30) NOT NULL,
    codcarr varchar(30) NOT NULL,
    codapod varchar(30) NOT NULL,
    monto numeric(12, 2),
    saldo numeric(12, 2),
    feccancel timestamp NOT NULL,
    codban numeric(5, 0) NOT NULL DEFAULT 0,
    plaza numeric(5, 0),
    fecven timestamp,
    recibido varchar(1) NOT NULL,
    estado numeric(2, 0) NOT NULL,
    fecreg timestamp NOT NULL,
    usuario varchar(8) NOT NULL,
    fecmod timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipocarr numeric(3, 0) NOT NULL,
    fecrep timestamp,
    fecimp timestamp,
    ano numeric(4, 0),
    periodo numeric(2, 0),
    ctatrans numeric(15, 0),
    caja integer,
    fecanula timestamp,
    fecha timestamp,
    codben numeric(5, 0),
    num_operacion numeric(22, 0),
    obestado varchar(50),
    folioprorrog numeric(18, 0),
    foliodevol numeric(18, 0),
    foliorepactacion numeric(18, 0),
    foliopago numeric(18, 0),
    glosa varchar(50),
    rut_gir varchar(20),
    nom_girador varchar(50),
    fono_girador varchar(50),
    ctacte varchar(50),
    moneda_ad numeric(1, 0),
    monto_ad numeric(18, 6),
    saldo_ad numeric(18, 6),
    paridad numeric(12, 4),
    saldoorigen numeric(10, 0),
    numop_mdf_contrato numeric(22, 0),
    jornada varchar(10),
    created_at timestamptz NOT NULL DEFAULT now(),
    origen text NOT NULL DEFAULT 'mol',
    CONSTRAINT pk_mnp_mt_ctapag PRIMARY KEY (ctapag, ctapagnum, codcli, codban)
);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctapag_codcli_periodo
    ON public.mnp_mt_ctapag (codcli, ano, periodo);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctapag_num_operacion
    ON public.mnp_mt_ctapag (num_operacion);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctapag_ctapagnum
    ON public.mnp_mt_ctapag (ctapagnum);

COMMENT ON TABLE public.mnp_mt_ctapag IS
    'Staging MOL espejo UMAS MT_CTAPAG (documentos de pago). No escribe en SQL Server.';

-- ---------------------------------------------------------------------------
-- mnp_mt_ctadep
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mnp_mt_ctadep (
    ctadoc numeric(4, 0) NOT NULL,
    ctadocnum numeric(15, 0) NOT NULL,
    ctapagnum numeric(15, 0) NOT NULL,
    ctapag numeric(4, 0) NOT NULL,
    codcli varchar(30) NOT NULL,
    codcarr varchar(30) NOT NULL,
    codapod varchar(30) NOT NULL,
    monto numeric(12, 2) NOT NULL,
    tipocarr numeric(3, 0) NOT NULL,
    fecmod timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario varchar(8) NOT NULL,
    ctatrans numeric(15, 0),
    fecimp timestamp,
    fecanulacion timestamp,
    estado varchar(30) DEFAULT '2',
    codban numeric(5, 0) NOT NULL DEFAULT 0,
    num_operacion numeric(22, 0),
    num_operanterior numeric(22, 0),
    oficinapago numeric(18, 0),
    caja integer,
    fecreg_dep timestamp DEFAULT CURRENT_TIMESTAMP,
    ano numeric(4, 0),
    lugarpago numeric(18, 0),
    saldoafavor varchar(1),
    moneda_ad numeric(1, 0),
    monto_ad numeric(18, 6),
    paridad_ad numeric(10, 4),
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    jornada varchar(10),
    created_at timestamptz NOT NULL DEFAULT now(),
    origen text NOT NULL DEFAULT 'mol',
    CONSTRAINT pk_mnp_mt_ctadep PRIMARY KEY (ctadoc, ctadocnum, ctapagnum, ctapag, codcli, codapod)
);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctadep_codcli
    ON public.mnp_mt_ctadep (codcli);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctadep_num_operacion
    ON public.mnp_mt_ctadep (num_operacion);

CREATE INDEX IF NOT EXISTS idx_mnp_mt_ctadep_ctadocnum
    ON public.mnp_mt_ctadep (ctadocnum);

COMMENT ON TABLE public.mnp_mt_ctadep IS
    'Staging MOL espejo UMAS MT_CTADEP (cruce documento-pago). No escribe en SQL Server.';

-- ---------------------------------------------------------------------------
-- RLS + grants
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'mnp_mt_docitem',
        'mnp_mt_ctadoc',
        'mnp_mt_ctapag',
        'mnp_mt_ctadep'
    ]
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);

        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_no_select_anon', t);
        EXECUTE format(
            'CREATE POLICY %I ON public.%I FOR SELECT TO anon USING (false)',
            t || '_no_select_anon', t
        );

        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_no_insert_anon', t);
        EXECUTE format(
            'CREATE POLICY %I ON public.%I FOR INSERT TO anon WITH CHECK (false)',
            t || '_no_insert_anon', t
        );

        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_no_select_authenticated', t);
        EXECUTE format(
            'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (false)',
            t || '_no_select_authenticated', t
        );

        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_no_insert_authenticated', t);
        EXECUTE format(
            'CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (false)',
            t || '_no_insert_authenticated', t
        );

        EXECUTE format(
            'GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO service_role',
            t
        );
    END LOOP;
END
$$;
